version: "3"
services:
  nezha-dashboard:
    image: whoer/nezha-dashboard
    container_name: nezha-dashboard
    restart: unless-stopped
    volumes:
      - /volume1/docker/neza/data:/dashboard/data
    ports:
      - 5500:80               # dashborad
      - 5555:5555           # client upload status
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"