{
 "title": "爱快网关监控",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(ikuai_version, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU使用率",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ikuai_cpu_usage_ratio{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_memory_usage_bytes{instance=\"$instance\"}/ikuai_memory_size_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_uptime{id=\"host\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_cpu_temperature{instance=\"$instance\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_network_conn_count{id=\"host\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "流量统计",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(increase(ikuai_network_send_bytes{id=~\"device/.*\", instance=\"$instance\"}[$__range]) * on(id, instance) group_left(comment, ip_addr) ikuai_device_info)",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(ikuai_network_recv_bytes{id=~\"device/.*\", instance=\"$instance\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "公网流量统计",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc((increase(ikuai_network_send_bytes{id=~\"iface/.*\", instance=\"$instance\"}[$__range]) and on(id) ikuai_uptime > 0) * on (id) group_left(interface, comment) ikuai_iface_info)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(increase(ikuai_network_recv_bytes{id=~\"iface/.*\", instance=\"$instance\"}[$__range]) and on(id) ikuai_uptime > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(ikuai_network_send_kbytes_per_second{id=~\"device/.*\", instance=\"$instance\"}* on (id, instance) group_left(ip_addr, hostname, comment, mac) ikuai_device_info)",
     "legendFormat": "__auto"
    },
    {
     "expr": "ikuai_network_recv_kbytes_per_second{id=~\"device/.*\", instance=\"$instance\"} * on (id) group_left(ip_addr, hostname, comment, mac) ikuai_device_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "ikuai_network_conn_count{id=~\"device/.*\", instance=\"$instance\"} * on (id) group_left ikuai_device_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "ikuai_network_send_kbytes_per_second{id=\"host\", instance=\"$instance\"}",
     "legendFormat": "netout"
    },
    {
     "expr": "ikuai_network_recv_kbytes_per_second{id=\"host\", instance=\"$instance\"}",
     "legendFormat": "netin"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(ikuai_network_send_kbytes_per_second{id=~\"iface/.*\"} and on(id) ikuai_uptime > 0) * on (id) group_left(interface, comment) ikuai_iface_info",
     "legendFormat": "{{comment}}-netout"
    },
    {
     "expr": "(ikuai_network_recv_kbytes_per_second{id=~\"iface/.*\"} and on(id) ikuai_uptime > 0) * on (id) group_left(interface, comment) ikuai_iface_info",
     "legendFormat": "{{comment}}-netin"
    }
   ]
  },
  {
   "title": "Device Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "ikuai_network_send_kbytes_per_second{id=~\"device/.*\", instance=\"$instance\"} * on (id) group_left(ip_addr, comment) ikuai_device_info",
     "legendFormat": "{{ip_addr}}-{{comment}}-send"
    },
    {
     "expr": "ikuai_network_recv_kbytes_per_second{id=~\"device/.*\", instance=\"$instance\"} * on (id) group_left(ip_addr, comment) ikuai_device_info",
     "legendFormat": "{{ip_addr}}-{{comment}}-recv"
    }
   ]
  },
  {
   "title": "Interface Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "ikuai_network_send_kbytes_per_second{id=~\"iface/.*\", instance=\"$instance\"} * on (id) group_left(interface, comment) ikuai_iface_info",
     "legendFormat": "{{interface}}-{{comment}}-send"
    },
    {
     "expr": "ikuai_network_recv_kbytes_per_second{id=~\"iface/.*\", instance=\"$instance\"} * on (id) group_left(interface, comment) ikuai_iface_info",
     "legendFormat": "{{interface}}-{{comment}}-recv"
    }
   ]
  }
 ]
}